/* eslint-disable prettier/prettier */
// /* eslint-disable prettier/prettier */
// /* eslint-disable @typescript-eslint/no-duplicate-enum-values */
// /* eslint-disable prettier/prettier */
// export enum Race {
//     // Canine
//     AKITA_INU = 'Akita Inu',
//     AMERICAN_PITBULL = 'American Pitbull',
//     BASSET_HOUND = 'Basset hound',
//     BEAGLE = 'Beagle',
//     BEARDED_COLLIE = 'Bearded Collie',
//     BERGER_ALLEMAND = 'Berger allemand',
//     BERGER_BELGE = 'Berger belge',
//     BERGER_BLANC_SUISSE = 'Berger Blanc Suisse',
//     BERGER_DU_CAUCASE = 'Berger du Caucase',
//     BERGER_KANGAL = 'Berger Kangal',
//     BICHON_FRISE = 'Bichon Frisé',
//     BICHON_HAVANAIS = 'Bichon havanais',
//     BICHON_MALTAIS = 'Bichon maltais',
//     BOBTAIL = 'Bobtail',
//     BORDER_COLLIE = 'Border collie',
//     BOULEDOGUE_FRANCAIS = 'Bouledogue français',
//     BOULEDOGUE_AMERICAIN = 'Bouledogue américain',
//     BOUVIER_BERNOIS = 'Bouvier bernois',
//     BOXER_ALLEMAND = 'Boxer allemand',
//     BRAQUE_FRANCAIS = 'Braque francais',
//     BRAQUE_ALLEMAND = 'Braque allemand',
//     BRAQUE_DE_WEIMAR = 'Braque de Weimar',
//     BULLDOG_ANGLAIS = 'Bulldog anglais',
//     BULL_TERRIER = 'Bull terrier',
//     BULLMASTIFF = 'Bullmastiff',
//     CANE_CORSO = 'Cane corso',
//     CANICHE = 'Caniche',
//     CAVALIER_KING_CHARLES_SPANIEL = 'Cavalier King Charles spaniel',
//     CHIHUAHUA = 'Chihuahua',
//     COCKER_SPANIEL = 'Cocker Spaniel',
//     COLLEY = 'Colley',
//     COTON_DE_TULEAR = 'Coton de Tuléar',
//     DALMATIEN = 'Dalmatien',
//     DOBERMANN = 'Dobermann',
//     DOGUE_ALLEMAND = 'Dogue allemand',
//     DOGUE_ARGENTIN = 'Dogue argentin',
//     DOGUE_DE_BORDEAUX = 'Dogue de Bordeaux',
//     DOGUE_DU_TIBET = 'Dogue du Tibet',
//     EPAGNEUL_BRETON = 'Épagneul breton',
//     EPAGNEUL_FRANCAIS = 'Épagneul Français',
//     FOX_TERRIER = 'Fox-terrier',
//     GOLDEN_RETRIEVER = 'Golden Retriever',
//     HUSKY_DE_SIBERIE = 'Husky de Sibérie',
//     JACK_RUSSELL_TERRIER = 'Jack Russell Terrier',
//     LABRADOR_RETRIEVER = 'Labrador Retriever',
//     LEVRIER = 'Lévrier',
//     MALAMUTE_DE_LALASKA = 'Malamute de l’Alaska',
//     MALINOIS = 'Malinois',
//     PEKINOIS = 'Pékinois',
//     PINSCHER = 'Pinscher',
//     ROTTWEILER = 'Rottweiler',
//     SAINT_BERNARD = 'Saint-bernard',
//     SAMOYEDE = 'Samoyède',
//     SLOUGHI = 'Sloughi',
//     TECKEL = 'Teckel',
//     YORKSHIRE_TERRIER = 'Yorkshire Terrier',
//     AUTRE = 'autre',
//     // Feline
//     ANGORA_TURC = 'Angora turc',
//     BLEU_RUSSE = 'Bleu Russe',
//     BENGAL = 'Bengal',
//     PERSAN = 'Persan',
//     HIMALAYEN = 'Himalayen',
//     MAINE_COON = 'Maine Coon',
//     RAGDOLL = 'Ragdoll',
//     SCOTTISH_FOLD = 'Scottish fold',
//     SIAMOIS = 'Siamois',
//     SPHYNX = 'Sphynx',
//     FELINE_AUTRE = 'autre',
//     // Other species can be added similarly
//   }
  